// Generated by continue
import { findLast, findLastIndex } from "./findLast";

describe("findLastIndex", () => {
  it("should return -1 for empty array", () => {
    const result = findLastIndex([], () => true);
    expect(result).toBe(-1);
  });

  it("should return -1 when no element matches criterion", () => {
    const arr = [1, 2, 3, 4, 5];
    const result = findLastIndex(arr, (x) => x > 10);
    expect(result).toBe(-1);
  });

  it("should return index of last element matching criterion", () => {
    const arr = [1, 2, 3, 2, 5];
    const result = findLastIndex(arr, (x) => x === 2);
    expect(result).toBe(3);
  });

  it("should return index of last matching element when multiple matches exist", () => {
    const arr = ["a", "b", "a", "c", "a"];
    const result = findLastIndex(arr, (x) => x === "a");
    expect(result).toBe(4);
  });

  it("should work with complex objects", () => {
    const arr = [
      { id: 1, name: "Alice" },
      { id: 2, name: "Bob" },
      { id: 3, name: "Alice" },
    ];
    const result = findLastIndex(arr, (x) => x.name === "Alice");
    expect(result).toBe(2);
  });

  it("should return index 0 when only first element matches", () => {
    const arr = [1, 2, 3];
    const result = findLastIndex(arr, (x) => x === 1);
    expect(result).toBe(0);
  });

  it("should return last index when only last element matches", () => {
    const arr = [1, 2, 3];
    const result = findLastIndex(arr, (x) => x === 3);
    expect(result).toBe(2);
  });

  it("should work with single element array that matches", () => {
    const arr = [42];
    const result = findLastIndex(arr, (x) => x === 42);
    expect(result).toBe(0);
  });

  it("should work with single element array that does not match", () => {
    const arr = [42];
    const result = findLastIndex(arr, (x) => x === 0);
    expect(result).toBe(-1);
  });
});

describe("findLast", () => {
  it("should return undefined for empty array", () => {
    const result = findLast([], () => true);
    expect(result).toBeUndefined();
  });

  it("should return undefined when no element matches criterion", () => {
    const arr = [1, 2, 3, 4, 5];
    const result = findLast(arr, (x) => x > 10);
    expect(result).toBeUndefined();
  });

  it("should return last element matching criterion", () => {
    const arr = [1, 2, 3, 2, 5];
    const result = findLast(arr, (x) => x === 2);
    expect(result).toBe(2);
  });

  it("should return last matching element when multiple matches exist", () => {
    const arr = ["first", "second", "third", "second"];
    const result = findLast(arr, (x) => x === "second");
    expect(result).toBe("second");
  });

  it("should work with complex objects and return the correct object", () => {
    const obj1 = { id: 1, name: "Alice" };
    const obj2 = { id: 2, name: "Bob" };
    const obj3 = { id: 3, name: "Alice" };
    const arr = [obj1, obj2, obj3];
    const result = findLast(arr, (x) => x.name === "Alice");
    expect(result).toBe(obj3);
  });

  it("should return first element when only it matches", () => {
    const arr = [1, 2, 3];
    const result = findLast(arr, (x) => x === 1);
    expect(result).toBe(1);
  });

  it("should return last element when only it matches", () => {
    const arr = [1, 2, 3];
    const result = findLast(arr, (x) => x === 3);
    expect(result).toBe(3);
  });

  it("should work with single element array that matches", () => {
    const arr = [42];
    const result = findLast(arr, (x) => x === 42);
    expect(result).toBe(42);
  });

  it("should work with single element array that does not match", () => {
    const arr = [42];
    const result = findLast(arr, (x) => x === 0);
    expect(result).toBeUndefined();
  });

  it("should handle truthy return values from criterion", () => {
    const arr = [0, "", null, undefined, "value", false];
    const result = findLast(arr, (x) => x);
    expect(result).toBe("value");
  });

  it("should handle falsy values in array correctly", () => {
    const arr = [0, false, "", 1];
    const result = findLast(arr, (x) => x === 0);
    expect(result).toBe(0);
  });
});
