// Generated by continue
import { isContinueTeamMember } from "./isContinueTeamMember";

describe("isContinueTeamMember", () => {
  it("should return true for emails ending with @continue.dev", () => {
    expect(isContinueTeamMember("john@continue.dev")).toBe(true);
  });

  it("should return true for any name before @continue.dev", () => {
    expect(isContinueTeamMember("jane.doe@continue.dev")).toBe(true);
    expect(isContinueTeamMember("test.user+tag@continue.dev")).toBe(true);
  });

  it("should return false for emails with different domains", () => {
    expect(isContinueTeamMember("john@example.com")).toBe(false);
    expect(isContinueTeamMember("john@gmail.com")).toBe(false);
    expect(isContinueTeamMember("john@other.dev")).toBe(false);
  });

  it("should return false for undefined email", () => {
    expect(isContinueTeamMember(undefined)).toBe(false);
  });

  it("should return false for empty string", () => {
    expect(isContinueTeamMember("")).toBe(false);
  });

  it("should return false for emails containing but not ending with @continue.dev", () => {
    expect(isContinueTeamMember("john@continue.dev.org")).toBe(false);
    expect(isContinueTeamMember("john@continue.developer.com")).toBe(false);
  });

  it("should be case-sensitive", () => {
    expect(isContinueTeamMember("john@CONTINUE.DEV")).toBe(false);
    expect(isContinueTeamMember("john@Continue.Dev")).toBe(false);
  });
});
